baseURL = 'https://mavtek-technologies.onrender.com'
languageCode = 'en-us'
title = 'Mavtek Technologies'
theme = 'hugo-universal-theme'
defaultContentLanguage = "en"

style = "default"

disqusShortname = "devcows"

[params]
    disabled_logo = false
    logo_text = "img/mavtek_logo.jpg"

    logo = "img/mavtek_logo.jpg"
    logo_small = "img/mavtek_logo.jpg"
    dropdown_mouse_over = true

# about_us

    about_us = "<p> Here at Mavtek Technologies, We aim to make all your web solutions come true.  Please contact me @ Wsewell36@proton.me</p>"

# contact_urls

    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong></strong>
        <br>(248) 318-2910
        <br>We are located in
        <br>Wixom,
        <strong> Michigan</strong>
      </p>
      """
    # defaultContentLanguage

  #  defaultKeywords = ["devcows", "hugo", "go"]
  #  defaultDescription = "Site template made by Devcows using Hugo"
  #  default_sharing_image = "img/sharing-default.png"
  #  facebook_site = "https://www.facebook.com/GolangSociety/"
  #  twitter_site = "GoHugoIO"
    
[[params.menu]]
   name = "Contact"
    url  = "/contact"
   weight = 4

#[[menu.main]]
#    name       = "Home"
#    identifier = "menu.home"
#    url        = "/"
#    weight     = 1

#[[menu.main]]
#    name       = "About"
#    identifier = "menu.about"
#    url        = "/"
#    weight     = 2

#[[menu.main]]
#    name        = "Resume"
#    identifier  = "menu.resume"
#    url         = "/about.md"
#    weight      = 3

#[[menu.main]]
#    name        = "Contact"
#    identifier  = "menu.contact"
#    url         = "/about.md"
#    weight      = 4

[params.widgets]
    search = true
    categories = true
    tags = true

[params.topbar]
    enable = true
    text = "<p> Mavtek Technologies </p>"

    [[menu.topbar]]
        weight = 1
        name = "GitHub"
        url = "https://github.com/maverik0071"
        pre = "<i class='fas fa-2x fa-github'></i>"

    [[menu.topbar]]
        weight = 2
        name = "Instagram"
        url = "http://instagram.com/Mavtek_teknologies"
        pre = "<i class='fas fa-2x fa-instagram'></i>"  

    banner = "img/banners/banner-4.jpg"

    [params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

    [params.features]
    enable = true
    cols = 4

    [params.testimonials]
    enable = false
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

    [params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "Fill Out The Form"
    link_url = "/https://localhost:1313/"
    link_text = "Click here Please"

    [params.clients]
    enable = false
    title = "Our Partners"
    subtitle = "We have proudly collaborated with the following companies."
    summaryLength = 70

    [params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellen"
    hide_summary = false



