baseURL = 'https://mavtek-web-technologies.onrender.com'
languageCode = 'en-us'
title = 'Mavtek Technologies'
theme = 'hugo-universal-theme'
defaultContentLanguage = "en"

style = "default"

disqusShortname = "devcows"

[params]
    disabled_logo = false
    logo_text = "Universal"

    logo = "img/mavtek_logo.jpg"
    logo_small = "mavtek_logo.jpg"
    dropdown_mouse_over = true

# about_us

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"

# contact_urls

    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
    # defaultContentLanguage

    defaultKeywords = ["devcows", "hugo", "go"]
    defaultDescription = "Site template made by Devcows using Hugo"
    default_sharing_image = "img/sharing-default.png"
    facebook_site = "https://www.facebook.com/GolangSociety/"
    twitter_site = "GoHugoIO"
    
[[params.menu]]
   #name = "Contact"
   # url  = "/contact"
   # weight = 4

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/"
    weight     = 2

[[menu.main]]
    name        = "Resume"
    identifier  = "menu.resume"
    url         = "/"
    weight      = 3

[[menu.main]]
    name        = "Contact"
    identifier  = "menu.contact"
    url         = "/"
    weight      = 4

[params.widgets]
    search = true
    categories = true
    tags = true

[params.topbar]
    enable = true
    text = "<p>Contact us on +420 777 555 333 or hello@universal.com.</p>"

    [[menu.topbar]]
        weight = 1
        name = "GitHub"
        url = "https://github.com/devcows/hugo-universal-theme"
        pre = "<i class='fas fa-2x fa-github'></i>"

    [[menu.topbar]]
        weight = 2
        name = "Facebook"
        url = "http://facebook.com"
        pre = "<i class='fas fa-2x fa-facebook'></i>"  

banner = "img/banners/banner-4.jpg"

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "http://your-site.com/more"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    title = "Our Partners"
    subtitle = "We have proudly collaborated with the following companies."
    summaryLength = 70

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellen"
    hide_summary = false



