baseURL = 'https://mavtek-web-technologies.onrender.com'
languageCode = 'en-us'
title = 'Mavtek Technologies'
theme = 'hugo-universal-theme'
defaultContentLanguage = "en"

style = "default"

disqusShortname = "devcows"

[params]
    disabled_logo = false
    logo_text = "Universal"

    logo = "img/mavtek_logo.jpg"
    logo_small = "mavtek_logo.jpg"



